import Footer from "@/components/dashboard/footer/Footer";
import Navbar from "@/components/dashboard/navbar/Navbar";
import type { Metadata } from "next";
import "../globals.css";


export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by Dashboard",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Navbar />

      <div className="h-[calc(100vh-172px)]">
        <div className="mx-auto max-w-[1240px]">
          {children}
        </div>
      </div>

      <Footer />
    </>
  );
}
